#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 2 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
    using WiFi.Entity;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WiFi/Views/DeviceHistory/_List_Toolbar.cshtml")]
    public partial class _Areas_WiFi_Views_DeviceHistory__List_Toolbar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_WiFi_Views_DeviceHistory__List_Toolbar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;

    var dic = new Dictionary<Int32, String>();
    dic.Add(1, "成功");
    dic.Add(0, "失败");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"tableTools-container list-toolbar\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"form-inline clear-fix\"");

WriteLiteral(">\r\n        <form");

WriteAttribute("action", Tuple.Create(" action=\"", 370), Tuple.Create("\"", 450)
            
            #line 15 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 379), Tuple.Create<System.Object, System.Int32>(Url.Action("index")
            
            #line default
            #line hidden
, 379), false)
            
            #line 15 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 399), Tuple.Create<System.Object, System.Int32>(Html.Raw("?" + page.GetBaseUrl(false, true, true))
            
            #line default
            #line hidden
, 399), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"pull-right form-group\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"type\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">类型：</label>\r\n");

WriteLiteral("                    ");

            
            #line 19 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.ForDropDownList("type", DeviceHistory.FindAllTypeName(), Request["type"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"action\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">操作：</label>\r\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.ForDropDownList("action", DeviceHistory.FindAllActionName(), Request["action"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"result\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">结果：</label>\r\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.ForDropDownList("result", dic, Request["result"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"dtStart\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">时间：</label>\r\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\r\n                        <input");

WriteLiteral(" name=\"dtStart\"");

WriteLiteral(" id=\"dtStart\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1589), Tuple.Create("\"", 1616)
            
            #line 33 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 1597), Tuple.Create<System.Object, System.Int32>(Request["dtStart"]
            
            #line default
            #line hidden
, 1597), false)
);

WriteLiteral(" dateformat=\"yyyy-MM-dd\"");

WriteLiteral(" class=\"form-control form_datetime\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <label");

WriteLiteral(" for=\"dtEnd\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">至</label>\r\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\r\n                        <input");

WriteLiteral(" name=\"dtEnd\"");

WriteLiteral(" id=\"dtEnd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2043), Tuple.Create("\"", 2068)
            
            #line 40 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 2051), Tuple.Create<System.Object, System.Int32>(Request["dtEnd"]
            
            #line default
            #line hidden
, 2051), false)
);

WriteLiteral(" dateformat=\"yyyy-MM-dd\"");

WriteLiteral(" class=\"form-control form_datetime\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"input-group btn-toolbar\"");

WriteLiteral(">\r\n                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"TokenID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2295), Tuple.Create("\"", 2319)
            
            #line 44 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 2303), Tuple.Create<System.Object, System.Int32>(page["TokenID"]
            
            #line default
            #line hidden
, 2303), false)
);

WriteLiteral(" />\r\n");

WriteLiteral("                    ");

            
            #line 45 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.Partial("_List_Toolbar_Search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                    ");

            
            #line 46 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.Partial("_List_Toolbar_Adv"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </form>\r\n    </div>\r\n</div>" +
"\r\n");

        }
    }
}
#pragma warning restore 1591
