#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Search.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Search.cshtml"
    using NewLife.Cube;
    
    #line default
    #line hidden
    using NewLife.Reflection;
    
    #line 2 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Search.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Search.cshtml"
    using WiFi.Entity;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Search.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/WiFi/Views/DeviceHistory/_List_Search.cshtml")]
    public partial class _Areas_WiFi_Views_DeviceHistory__List_Search_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_WiFi_Views_DeviceHistory__List_Search_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Search.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;

    var dic = new Dictionary<Int32, String>();
    dic.Add(1, "成功");
    dic.Add(0, "失败");

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"action\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">操作：</label>\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Search.cshtml"
Write(Html.ForDropDownList("action", DeviceHistory.FindAllActionName(), Request["action"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n<div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n    <label");

WriteLiteral(" for=\"result\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">结果：</label>\r\n");

WriteLiteral("    ");

            
            #line 20 "..\..\Areas\WiFi\Views\DeviceHistory\_List_Search.cshtml"
Write(Html.ForDropDownList("success", dic, Request["success"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
