#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
    using NewLife;
    
    #line default
    #line hidden
    using NewLife.Cube;
    using NewLife.Reflection;
    
    #line 2 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
    using NewLife.Web;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
    using XCode;
    
    #line default
    #line hidden
    using XCode.Membership;
    
    #line 4 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
    using xLink.Entity;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Device/Views/DeviceHistory/_List_Toolbar.cshtml")]
    public partial class _Areas_Device_Views_DeviceHistory__List_Toolbar_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Device_Views_DeviceHistory__List_Toolbar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
  
    var fact = ViewBag.Factory as IEntityOperate;
    var page = ViewBag.Page as Pager;

    var dic = new Dictionary<Int32, String>();
    dic.Add(1, "成功");
    dic.Add(0, "失败");

            
            #line default
            #line hidden
WriteLiteral("\n<div");

WriteLiteral(" class=\"tableTools-container list-toolbar\"");

WriteLiteral(">\n    <div");

WriteLiteral(" class=\"form-inline clear-fix\"");

WriteLiteral(">\n        <form");

WriteAttribute("action", Tuple.Create(" action=\"", 357), Tuple.Create("\"", 437)
            
            #line 15 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 366), Tuple.Create<System.Object, System.Int32>(Url.Action("index")
            
            #line default
            #line hidden
, 366), false)
            
            #line 15 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 386), Tuple.Create<System.Object, System.Int32>(Html.Raw("?" + page.GetBaseUrl(false, true, true))
            
            #line default
            #line hidden
, 386), false)
);

WriteLiteral(" method=\"post\"");

WriteLiteral(" role=\"form\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"pull-right form-group\"");

WriteLiteral(">\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n                    <label");

WriteLiteral(" for=\"type\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">类型：</label>\n");

WriteLiteral("                    ");

            
            #line 19 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.ForDropDownList("type", DeviceHistory.FindAllTypeName(), Request["type"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\n                </div>\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n                    <label");

WriteLiteral(" for=\"action\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">操作：</label>\n");

WriteLiteral("                    ");

            
            #line 23 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.ForDropDownList("action", DeviceHistory.FindAllActionName(), Request["action"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\n                </div>\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n                    <label");

WriteLiteral(" for=\"result\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">结果：</label>\n");

WriteLiteral("                    ");

            
            #line 27 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.ForDropDownList("result", dic, Request["result"], "全部", true));

            
            #line default
            #line hidden
WriteLiteral("\n                </div>\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n                    <label");

WriteLiteral(" for=\"dtStart\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">时间：</label>\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\n                        <input");

WriteLiteral(" name=\"dtStart\"");

WriteLiteral(" id=\"dtStart\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1558), Tuple.Create("\"", 1585)
            
            #line 33 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 1566), Tuple.Create<System.Object, System.Int32>(Request["dtStart"]
            
            #line default
            #line hidden
, 1566), false)
);

WriteLiteral(" dateformat=\"yyyy-MM-dd\"");

WriteLiteral(" class=\"form-control form_datetime\"");

WriteLiteral(" />\n                    </div>\n                </div>\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\n                    <label");

WriteLiteral(" for=\"dtEnd\"");

WriteLiteral(" class=\"control-label\"");

WriteLiteral(">至</label>\n                    <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\n                        <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-calendar\"");

WriteLiteral("></i></span>\n                        <input");

WriteLiteral(" name=\"dtEnd\"");

WriteLiteral(" id=\"dtEnd\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2005), Tuple.Create("\"", 2030)
            
            #line 40 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 2013), Tuple.Create<System.Object, System.Int32>(Request["dtEnd"]
            
            #line default
            #line hidden
, 2013), false)
);

WriteLiteral(" dateformat=\"yyyy-MM-dd\"");

WriteLiteral(" class=\"form-control form_datetime\"");

WriteLiteral(" />\n                    </div>\n                </div>\n                <div");

WriteLiteral(" class=\"input-group btn-toolbar\"");

WriteLiteral(">\n                    <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"TokenID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2253), Tuple.Create("\"", 2277)
            
            #line 44 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
, Tuple.Create(Tuple.Create("", 2261), Tuple.Create<System.Object, System.Int32>(page["TokenID"]
            
            #line default
            #line hidden
, 2261), false)
);

WriteLiteral(" />\n");

WriteLiteral("                    ");

            
            #line 45 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.Partial("_List_Toolbar_Search"));

            
            #line default
            #line hidden
WriteLiteral("\n");

WriteLiteral("                    ");

            
            #line 46 "..\..\Areas\Device\Views\DeviceHistory\_List_Toolbar.cshtml"
               Write(Html.Partial("_List_Toolbar_Adv"));

            
            #line default
            #line hidden
WriteLiteral("\n                </div>\n            </div>\n        </form>\n    </div>\n</div>\n");

        }
    }
}
#pragma warning restore 1591
